apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexusapp-ecr
  labels:
    app: nexusapp-ecr
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nexusapp-ecr
  template:
    metadata:
      labels:
        app: nexusapp-ecr
    spec:
      containers:
      - name: nexusapp-ecr
        image: 442426854264.dkr.ecr.eu-west-1.amazonaws.com/nx-poc-pipeline:1.0
        ports:
        - containerPort: 8080
